### PR TITLE
fix: Remove google guava dep that suppressed gRPC

### LINKED ISSUE #158: v0.5.0 agent isn't working on its own
**Versions**

- Java: 11
- Honeycomb OpenTelemetry Distribution: v0.5.0

**Steps to reproduce**

Run agent alongside app with no SDK

**Additional context**

With same setup, vanilla otel agent 1.6.1 and java distro 0.4.0 shows some trace data in honeycomb. Nothing shows up with 0.5.0 agent.

### PR DESCRIPTION
**Pull request by JamieDanielson**
## Which problem is this PR solving?

- Closes #158 
- In [v0.5.0](https://github.com/honeycombio/honeycomb-opentelemetry-java/releases/tag/v0.5.0) we enabled support for metrics, and introduced a new dependency on `com.google.guava:guava:30.1.1-jre` to detect the existence of a metrics dataset. Somehow this library prevents the agent from working on its own without manually adding a dependency on gRPC (either via direct dependency or transitive through sdk).

## Short description of the changes

- This PR removes that dependency, but still checks whether the metrics dataset variable is null.

To confirm it works, remove the `:sdk` dependency and manual instrumenting from the spring-agent example app, and `../../gradlew bootRun` from sprint-agent directory. Curling the endpoint should produce telemetry in honeycomb (enable `OTEL_JAVAAGENT_DEBUG` to see in console as well).

### CODE REVIEW

File: common/src/main/java/io/honeycomb/opentelemetry/EnvironmentConfiguration.java [hunk 1]
```diff
@@ -181,11 +179,11 @@ public static void enableOTLPMetrics() {
         final String apiKey = getHoneycombMetricsApiKey();
         final String dataset = getHoneycombMetricsDataset();
 
-        if (!Strings.isNullOrEmpty(dataset)) {
+        if (dataset != null) {
```
Comment (bdarfler) [inline common/src/main/java/io/honeycomb/opentelemetry/EnvironmentConfiguration.java:182]: Is it worth duplicating the empty check as well?

https://github.com/google/guava/blob/master/android/guava/src/com/google/common/base/Platform.java#L58-L60

Comment (JamieDanielson) [reply common/src/main/java/io/honeycomb/opentelemetry/EnvironmentConfiguration.java]: Ah, yes of course! 👍  I've updated to use `isPresent`, which checks for both null and empty: `return value != null && !value.isEmpty();`

Comment (bdarfler) [reply common/src/main/java/io/honeycomb/opentelemetry/EnvironmentConfiguration.java]: Oh look at that, we already had one!

**Review by bdarfler — APPROVED** [review]

**Review by vreynolds — APPROVED** [review]
