### PR TITLE
Decorate existing Sampler with DeterministicTraceSampler instead of replacing it

### LINKED ISSUE #315: Agent Auto Configuration can overwrite an extension's customer Sampler
## Headline
The way [HoneycombAutoConfigurationCustomizerProvider](https://github.com/honeycombio/honeycomb-opentelemetry-java/blob/main/custom/src/main/java/io/honeycomb/opentelemetry/HoneycombAutoConfigurationCustomizerProvider.java) is written, (calling `SdkTracerProviderBuilder.setSampler()`), it can overwrite a `Sampler` installed by an OTel Java Agent extension that is intended to decorate whatever other sampling is in place.

## Versions

- Honeycomb OpenTelemetry Distribution: 1.2.0

## Steps to reproduce

1. Create an OTel extension that auto-configures a custom OTel `Sampler`, decorating the already installed one. (This is not a trivial task. You can see some of the steps I've taken to do this [here](https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/5008). But the bug is pretty obvious from the code.)
2. Run an app with the Honeycomb agent and the custom extension.

## Expected Behaviour
`HoneycombAutoConfigurationCustomizerProvider` should customize (i.e. decorate) any `Sampler` already in the configuration, so that the extension's `Sampler` decorating behaviour is effective, irrespective of what order `AutoConfigurationCustomizerProvider`s are loaded.

## Actual Behaviour
Depending on the order in which Java's `ServiceLoader` loads the two `AutoConfigurationCustomizerProvider`s (Honeycomb's and the extension's), it's possible (and happens consistently, for me) that Honeycomb's code overwrites the extension's custom `Sampler`.

## Additional context
The `HoneycombAutoConfigurationCustomizerProvider` overwrites whatever sampler is in the configuration already:
https://github.com/honeycombio/honeycomb-opentelemetry-java/blob/fd6a2a2613bb3a68b3c7fb0734533266d66165eb/custom/src/main/java/io/honeycomb/opentelemetry/HoneycombAutoConfigurationCustomizerProvider.java#L31-L33

I can't see any way to control the order in which `AutoConfigurationCustomizerProvider`s are executed, either in the `ServiceLoader` feature or in the design/usage of `AutoConfigurationCustomizerProvider` (in OTel's `AutoConfiguredOpenTelemetrySdkBuilder.build()`).

Honeycomb's auto config should probably, instead of setting the `Sampler`, decorate whatever `Sampler` is already installed, using the `addSamplerCustomizer()` extension point, as shown here:
https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/5008#issuecomment-1163162647

### PR DESCRIPTION
**Pull request by GrahamLea**
## Which problem is this PR solving?

Fixes #315: Agent Auto Configuration can overwrite an extension's customer Sampler

## Short description of the changes

Changes the way the Honeycomb agent configures the tracer by decorating the existing Sampler rather than replacing it. Also changes the implementation of DeterministicTraceSampler to function as a decorating/filtering Sampler rather than 100% authoritative.

### CODE REVIEW

File: common/src/main/java/io/honeycomb/opentelemetry/sdk/trace/samplers/DeterministicTraceSampler.java [hunk 1]
```diff
@@ -78,10 +98,18 @@ public SamplingResult shouldSample(
         Attributes attributes,
         List<LinkData> parentLinks) {
 
-        SamplingResult result = baseSampler.shouldSample(parentContext, traceId, name, spanKind, attributes, parentLinks);
-        return SamplingResult.create(
-            result.getDecision(),
-            Attributes.of(SAMPLE_RATE_ATTRIBUTE_KEY, (long) sampleRate)
-        );
+        SamplingResult result =
```
Comment (MikeGoldsmith) [inline common/src/main/java/io/honeycomb/opentelemetry/sdk/trace/samplers/DeterministicTraceSampler.java:101]: Looks like we're using the decoratedSampler then the baseSampler but the the comments indicate we expect the basSampler to execute first, then the decorated sampler.

This need to be consistent to ensure we get the expected behaviour.

File: common/src/test/java/io/honeycomb/opentelemetry/sdk/trace/samplers/DeterministicTraceSamplerTest.java [hunk 2]
```diff
@@ -1,24 +1,26 @@
...
+import java.util.Collections;
+import java.util.List;
 
 public class DeterministicTraceSamplerTest {
 
     @Test
     public void test_neverSample() {
         int sampleRate = 0;
-        Sampler sampler = new DeterministicTraceSampler(sampleRate);
+        Sampler sampler = new DeterministicTraceSampler(Sampler.alwaysOn(), sampleRate);
```
Comment (MikeGoldsmith) [inline common/src/test/java/io/honeycomb/opentelemetry/sdk/trace/samplers/DeterministicTraceSamplerTest.java:23]: I guess this isn't strictly needed as we have a constructor that just takes the sampleRate param. We exercise the the constructor in later tests to provide a decordatedSampler.

**Review by MikeGoldsmith — CHANGES_REQUESTED** [review]
Thanks @GrahamLea - this looks great.

I've left a query regarding execution order of the decorated & base samplers and a suggestion to use the original constructor.

File: common/src/main/java/io/honeycomb/opentelemetry/sdk/trace/samplers/DeterministicTraceSampler.java (hunk 1 above)
Comment (GrahamLea) [reply common/src/main/java/io/honeycomb/opentelemetry/sdk/trace/samplers/DeterministicTraceSampler.java:101]: Yes! Good pick up.

The implementation ended up this way because I figured it made sense to always include the `decoratedSampler`'s attributes, regardless of what the decision was. `baseSampler`, on the other hand, we know delivers no attributes in its result, so we lose nothing by skipping it.

I'll update the comment to match the implementation.

**Review by MikeGoldsmith — APPROVED** [review]
Looks great, thanks @GrahamLea 👍🏻
